---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: "abinayaelango/jen-docker:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
